templates:
  template.yml:
    demo:
      demo:
        event: default_evt
        events:
          default_evt:
            type: file
            value: demo\demo\event.evt
    demo-service:
      pyq:
        event: default_evt
        events:
          default_evt:
            type: file
            value: demo-service\pyq\event.evt
      demo:
        event: default_evt
        events:
          default_evt:
            type: file
            value: demo-service\demo\event.evt
